; ---------------------------------------------------------------------------
;  PlatformIO Project Configuration
;  Documentacion: https://docs.platformio.org/page/projectconf.html
; ---------------------------------------------------------------------------

[env:promicro]
platform = atmelavr
board = sparkfun_promicro16      ; Arduino Pro Micro (ATmega32U4, 5 V / 16 MHz)
framework = arduino

monitor_speed = 115200
;monitor_filters = time, default

build_flags =
    -Wall
